codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "50...80"
  status:
    project:
      default:
        target: auto
        threshold: 2%
        if_not_found: success
    patch:
      default:
        target: auto
        threshold: 5%
        if_not_found: success

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "src/**/__tests__/**" 